describe('struct', function()
  local newtype = require('wowless.struct')
  it('works on empty struct', function()
    local new = newtype('foo', {})
    assert.same('function', type(new))
    local obj = new()
    assert.same('userdata', type(obj))
    assert.same('foo', getmetatable(obj))
    assert.errors(function() return obj.bar end, 'unknown field')
    assert.errors(function() obj.bar = 42 end, 'unknown field')
  end)
  it('works on nonempty struct', function()
    local new = newtype('foo', { bar = 'number' })
    assert.same('function', type(new))
    local obj = new()
    assert.same('userdata', type(obj))
    assert.same('foo', getmetatable(obj))
    assert.Nil(obj.bar)
    obj.bar = 42
    assert.same(42, obj.bar)
    assert.errors(function() obj.bar = 'baz' end, 'type mismatch')
  end)
end)
