name: test
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: .devcontainer/Dockerfile
        load: true
        tags: moo
    - run: docker run -t -v $PWD:/moo moo bash -c \
           "cd /moo && bash -c $(jq .postCreateCommand .devcontainer/devcontainer.json)"
